targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/shared/confio** # Your .proto directory
    builders:
      protoc_builder:
        options:
          # The version of the Protobuf compiler to use.
          protobuf_version: "3.19.1" # Make sure to use quotation marks.
          # The version of the Dart protoc_plugin package to use.
          protoc_plugin_version: "20.0.0" # Make sure to use quotation marks.
          # Include paths given to the Protobuf compiler during compilation.
          proto_paths:
            - "lib/shared/confio/"
          # The root directory for generated Dart output files.
          out_dir: "lib/generated"
          grpc: true