name: terra_dart
description: TerraDart is the Dart Implementation of Terra.js, the TypeScript Library for developing on Terra Luna. Library For Flutter & Dart Applications
version: 1.0.0
homepage: https://github.com/terra-rebels/terra-dart

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  path: ^1.8.0
  node_interop: ^2.1.0
  buffer: ^1.1.1
  http: ^0.13.5
  bech32: ^0.2.1
  bip32: ^2.0.0
  bip39: ^1.0.6
  decimal: ^2.2.0
  crypto: ^3.0.2
  secp256k1: ^0.3.0
  validated: ^2.0.0
  protobuf: ^2.1.0
  web_socket_channel: ^2.2.0
  hash: ^1.0.4
  bloc: ^8.1.0
  flutter_simple_dependency_injection: ^2.0.0
  grpc: ^3.1.0
  protobuf_google: ^0.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
